// Add this lookup table at the top of the file, outside the component
const STAR_PLAYER_NAMES = {
  'GRIFFOBERWALD': 'Griff Oberwald',
  'HUMAIN': 'Griff Oberwald',
  'JORDELLFRESHBREEZE': 'Jordell Freshbreeze',
  'ELFE_SYLVAIN': 'Jordell Freshbreeze',
  'ELDRILSIDEWINDER': 'Eldril Sidewinder',
  'PRINCE_MORANION': 'Prince Moranion',
  'MORANION': 'Prince Moranion',
  'ZZHARGMADEYE': 'Zzharg Madeye',
  'NOBBLABLACKWART': 'Nobbla Blackwart',
  'NOBBLA': 'Nobbla Blackwart',
  'PUGGY_BACONBREATH': 'Puggy Baconbreath',
  'PUGGY': 'Puggy Baconbreath',
  'THE_BLACK_GOBBO': 'The Black Gobbo',
  'BOMBERDRIBBLESNOT': 'Bomber Dribblesnot',
  'DRIBBLESNOT': 'Bomber Dribblesnot',
  'FUNGUS': 'Fungus the Loon',
  'FUNGUS_THE_LOON': 'Fungus the Loon',
  'RIPPERBOLGROT': 'Ripper Bolgrot',
  'SCRAPPASOREHEAD': 'Scrappa Sorehead',
  'MIGHTYZUG': 'Mighty Zug',
  'MIGHTY_ZUG': 'Mighty Zug',
  'LORD_BORAK': 'Lord Borak the Despoiler',
  'LORDBORAKTHEDESPOILER': 'Lord Borak the Despoiler',
  'UGROTH_BOLGROT': 'Ugroth Bolgrot',
  'MORGNTHORG': "Morg 'n' Thorg",
  'MORG': "Morg 'n' Thorg",
  'HAKFLEM': 'Hakflem Skuttlespike',
  'HAKFLEMSKUTTLESPIKE': 'Hakflem Skuttlespike',
  'HAKFLEM_SKUTTLESPIKE': 'Hakflem Skuttlespike',
  'HEADSPLITTER': 'Headsplitter',
  'SKRORG_SNOWPELT': 'Skrorg Snowpelt',
  'ICEPELT_HAMMERBLOW': 'Icepelt Hammerblow',
  'DEEPROOTSTRONGBRANCH': 'Deeproot Strongbranch',
  'DOLFAR': 'Dolfar Longstride',
  'DOLFAR_LONGSTRIDE': 'Dolfar Longstride',
  'LOTTABOTTOL': 'Lottabottol',
  'THORSSON_STOUTMEAD': 'Thorsson Stoutmead',
  'BARIK': 'Barik Farblast',
  'BARIK_FARBLAST': 'Barik Farblast',
  'GRIM_IRONJAW': 'Grim Ironjaw',
  'NAIN': 'Grim Ironjaw',
  'BOOMER': 'Boomer Eziasson',
  'BOOMER_EZIASSON': 'Boomer Eziasson',
  'FLINT': 'Flint Churnblade',
  'FLINT_CHURNBLADE': 'Flint Churnblade',
  'ROXANNA_DARKNAIL': 'Roxanna Darknail',
  'LUCIEN_SWIFT': 'Lucien Swift',
  'LOREN_FOREST-STRIDER': 'Loren Forest-Strider',
  'HUBRIS_RAKARTH': 'Hubris Rakarth',
  'HORKON_HEARTRIPPER': 'Horkon Heartripper',
  'SCYLA_ANFINGRIMM': 'Scyla Anfingrimm',
  'MAX_SPLEENRIPPER': 'Max Spleenripper',
  'KREEK_RUSTGOUGER': 'Kreek Rustgouger',
  'GROTTY': 'Grotty',
  'LEWDGRIP_WHIPARM': 'Lewdgrip Whiparm',
  'COUNT_LUTHOR_VON_DRAKENBORG': 'Count Luthor von Drakenborg',
  'SINNEDBAD': 'Sinnedbad',
  'RAMTUTIII': 'Ramtut III',
  'RAMTUT_III': 'Ramtut III',
  'SETEKH': 'Setekh',
  'SOKAR_MISTRALSSON': 'Sokar Mistralsson',
  'CRAZY_IGOR': 'Crazy Igor',
  'FRANK_N_STEIN': "Frank 'n' Stein",
  'WILHELM': 'Wilhelm Chaney',
  'WILHELM_CHANEY': 'Wilhelm Chaney',
  'JEARLICE': 'J. Earlice',
  'J_EARLICE': 'J. Earlice',
  'HELMUT_WULF': 'Helmut Wulf',
  'HELMUT': 'Helmut Wulf',
  'UNDEAD': 'Count Luthor von Drakenborg',
  'HACK': 'Hack Enslash',
  'ZARATHESLAYER': 'Zara the Slayer',
  'HTHARK': 'Hthark the Unstoppable',
  'HOMME_LEZARD': 'Slibli',
  'NEKBREKEREKH': 'Setekh',
  'BERTHA': 'Bertha Bigfist',
  'BRICK': 'Brick',
  'GROTTY': 'Grotty',
  'IGOR': 'Crazy Igor',
  'FEZGLITCH': 'Fezglitch',
  'GLART': 'Glart',
  'CHAOS': 'Grashnak Blackhoof',
  'SKAVEN': 'Headsplitter',
  'HEMLOCK': 'Hemlock',
  'DARKELF': 'Horkon Heartripper',
  'HUBRISRAKARTH': 'Hubris Rakarth',
  'HUMERUS': 'Humerus Carpal',
  'ICEPELTHAMMERBLOW': 'Icepelt Hammerblow',
  'ITHACA': 'Ithaca Benoin',
  'LEWDGRIP': 'Lewdgrip Whiparm',
  'LUCIENSWIFT': 'Lucien Swift',
  'LOTTABOTTOL': "Lottabottol",
  'MAXSPLEENRIPPER': "Max Spleenripper",
  'QUETZAL': "QuetzaL Leap",
  'RASHNAK': "Rashnak Backstabber",
  'GOBELIN': "Ripper Bolgrot",
  'ROXANNA': "Roxanna Darknail",
  'SCRAPPASOREHEAD': "Scrappa Sorehead",
  'SINNEDBAD': "Sinnedbad",
  'SKITTER': "Skitter Stab-Stab",
  'SKRORG': "Skrorg Snowpelt",
  'SOAREN': "Soaren Hightower",
  'UGROTH': "Ugroth Bolgrot",
  'ORC': "Varag Ghoulchewer",
  'VARAG': "Varag Ghoulchewer",
  'WILLOW': "Willow Rosebark",
  'ZZHARGMADEYE': "Zzharg Madeye",
  'BRICK': "Brick Far\'th",
  'ASPERON': "Asperon Thorn",
  'IVAN': "Ivan Deathshroud",
  'IVAR': "Ivar Eriksson",
  'KREEK': "Kreek Rustgouger",
  'ZOLCATH': "Zolcath the Zoat",
  'CINDY': "Cindy Piewhistle",
};

// Helper function to check if a player is a star player and get their display name
export const getStarPlayerDisplayName = (playerName) => {
  return STAR_PLAYER_NAMES[
    playerName
      .replace('_FALLBACK', '')
      .replace('PLAYER_NAMES_CHAMPION_', '')
      .replace('name_sp_', '')
      .toUpperCase()
  ] || playerName;
};

export const isStarPlayer = (playerName) => {
  return playerName && (playerName.startsWith("PLAYER_NAMES_CHAMPION_") || playerName.startsWith ("name_sp_"));
}