import React from 'react';
import { Badge, Tab, TabList, TabPanel, TabPanels, Tabs, Table, TableContainer, Tbody, Td, Text, Th, Thead, Tr } from '@chakra-ui/react';
import prettyPrint from '../../util/prettyPrint';
import { resolveRace } from '../../util/raceUtil';
const desktop={display:{base:'none',lg:'table-cell'}},tablet={display:{base:'none',md:'table-cell'}};
export function PlayerTable({category}){return <TableContainer><Table size="sm"><Thead><Tr><Th>#</Th><Th>Player</Th><Th>Team</Th><Th isNumeric>{category.label}</Th><Th {...tablet}>Coach</Th><Th {...desktop}>Race / position</Th><Th {...desktop} isNumeric>Games</Th><Th {...desktop} isNumeric>SPP</Th><Th {...desktop}>Skills</Th></Tr></Thead><Tbody>{category.entries.map((p,i)=><Tr key={`${p.playerId}-${i}`}><Td>{i+1}</Td><Td fontWeight="bold">{p.name||'Unknown player'}</Td><Td>{p.teamName||'Unknown team'}</Td><Td isNumeric fontWeight="bold">{p.value}</Td><Td {...tablet}>{p.coachName||'–'}</Td><Td {...desktop}>{prettyPrint(resolveRace(p,p.opus))} · {prettyPrint(p.position)||'–'}</Td><Td {...desktop} isNumeric>{p.games}</Td><Td {...desktop} isNumeric>{p.spp}</Td><Td {...desktop} maxW="24rem" whiteSpace="normal">{p.skills?.map(prettyPrint).join(', ')||'–'}</Td></Tr>)}</Tbody></Table></TableContainer>}
export function TeamTable({category,entries}){const rows=entries||category.entries;return <TableContainer><Table size="sm"><Thead><Tr><Th>#</Th><Th>Team</Th><Th isNumeric>{category?.label||'Points'}</Th><Th {...tablet}>Coach</Th><Th {...desktop}>Edition</Th><Th {...desktop} isNumeric>G</Th><Th {...desktop} isNumeric>W-D-L</Th><Th {...desktop} isNumeric>TD +/-</Th><Th {...desktop} isNumeric>CAS +/-</Th></Tr></Thead><Tbody>{rows.map((t,i)=><Tr key={`${t.teamId}-${i}`}><Td>{i+1}</Td><Td fontWeight="bold">{t.name}</Td><Td isNumeric fontWeight="bold">{t.value??t.points}</Td><Td {...tablet}>{t.coachName||'–'}</Td><Td {...desktop}>{t.editions?.map(e=><Badge key={e} mr={1}>{e}</Badge>)}</Td><Td {...desktop} isNumeric>{t.games}</Td><Td {...desktop} isNumeric>{t.wins}-{t.draws}-{t.losses}</Td><Td {...desktop} isNumeric>{t.touchdownsFor}-{t.touchdownsAgainst}</Td><Td {...desktop} isNumeric>{t.casualtiesFor}-{t.casualtiesAgainst}</Td></Tr>)}</Tbody></Table></TableContainer>}
export function CategoryTabs({categories,type}){if(!categories?.length)return <Text color="gray.500">No statistics are available for this selection.</Text>;return <Tabs variant="enclosed" isLazy><TabList overflowX="auto">{categories.map(c=><Tab flexShrink={0} key={c.key}>{c.label}</Tab>)}</TabList><TabPanels>{categories.map(c=><TabPanel px={0} key={c.key}>{type==='player'?<PlayerTable category={c}/>:<TeamTable category={c}/>}</TabPanel>)}</TabPanels></Tabs>}
export function VersusTable({rows}){if(!rows?.length)return <Text color="gray.500">No opponents found for the mapped coach IDs.</Text>;return <TableContainer><Table size="sm"><Thead><Tr><Th>Coach</Th><Th isNumeric>G</Th><Th isNumeric>W-D-L</Th><Th isNumeric>TD</Th><Th isNumeric>CAS</Th></Tr></Thead><Tbody>{rows.map(v=><Tr key={v.coachId}><Td fontWeight="bold">{v.coachName||v.coachId}</Td><Td isNumeric>{v.games}</Td><Td isNumeric>{v.wins}-{v.draws}-{v.losses}</Td><Td isNumeric>{v.touchdownsFor}-{v.touchdownsAgainst}</Td><Td isNumeric>{v.casualtiesFor}-{v.casualtiesAgainst}</Td></Tr>)}</Tbody></Table></TableContainer>}
