stages:
  - build
  - test
  - package
  - deploy
  - release

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository
    - target

maven-build:
  stage: build
  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release-.*/
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always
  script: "mvn -Ddockerfile.skip clean compile --batch-mode"

maven-test:
  stage: test
  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release-/
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always
  script: "mvn test --fail-at-end --batch-mode"
  artifacts:
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/junit.xml"

maven-package:
  stage: package
  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
  only:
    - /^dev$/
  script: "mvn -DskipTests=true install"

maven-deploy:
  stage: deploy
  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
  only:
    - /^dev$/
  script: "mvn -DskipTests=true deploy -s ci_settings.xml"

maven-release:
  stage: release
  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
  only:
    - /^main$/
  before_script:
    # Set the displayed user with the commits that are about to be made
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
    # Create a new branch to work on
    - nextReleaseVersion=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed 's/-SNAPSHOT//')
    - releaseBranchName="release-${nextReleaseVersion}-${CI_COMMIT_SHORT_SHA}"
    - git remote set-url origin "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git checkout -B "${releaseBranchName}"
  script:
    - ./updateChangelog.sh "${nextReleaseVersion}"
    - git commit -a -m "Updated changelog for release ${nextReleaseVersion} (${CI_COMMIT_SHORT_SHA})"
    - git push --set-upstream origin "${releaseBranchName}"
    - mvn -DskipTests=true release:prepare release:perform --batch-mode -s ci_settings.xml -DpushChanges=false
    - git commit -a -m "Performed release ${nextReleaseVersion} (${CI_COMMIT_SHORT_SHA})"
    - git push origin "${releaseBranchName}"
#    - git checkout dev
#    - git merge --no-ff ${CI_COMMIT_REF_NAME}
#    - git push origin dev



#
#
#maven-release:
#  stage: package
#  only:
#    - /^main$/
#  image: registry.hub.docker.com/library/maven:3.8-openjdk-17
#  script: "mvn release:prepare release:perform -DskipTests=true"

