include:
  - component: gitlab.com/to-be-continuous/maven/gitlab-ci-maven@3.9.0
    inputs:
      image: registry.hub.docker.com/library/maven:3.8-openjdk-17

stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn -Pno-docker clean verify

build:
  stage: build
  script:
    - mvn clean install
