app = "cyanidebowl"

[build]
  # Uncomment if you want to specify a Dockerfile path
  dockerfile = "backend/docker/Dockerfile"

[env]
  SPRING_DATA_MONGODB_URI="mongodb+srv://rw:rw@nst-cluster.9a9lw.mongodb.net/cyanidebowl"
  CYANIDE_API_KEY="57870960b7159cc1b01710a789f928d4"
  SERVER_PORT="8080"
  BACKEND_URI="https://cyanidebowl.fly.dev"
  FRONTEND_URI="https://bloodbowl.granasen.com"
  REACT_APP_BACKEND_URI="https://bloodbowl.granasen.com"
 
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443