package net.warp_scores.warpscores.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@Document("articles")
@CompoundIndex(name = "article_slug_unique", def = "{'slug': 1}", unique = true)
public class Article {
    public enum Status { DRAFT, PUBLISHED, ARCHIVED }
    public enum AuthorType { HUMAN, AI_REPORTER }

    @Id
    private String id;
    private String leagueSystemId;
    private String seasonId;

    /**
     * Legacy author classification kept temporarily for stored documents and old readers.
     * New code must use authorUserId for identity and generation for provenance.
     */
    @Deprecated
    private AuthorType authorType = AuthorType.HUMAN;
    @Deprecated
    private String authorAgentId;

    private Long authorUserId;
    /**
     * Null is valid for legacy content whose generation provenance is unknown.
     */
    private GenerationProvenance generation;
    private String authorSubject;
    private String authorDisplayName;
    private String title;
    private String slug;
    private String excerpt;
    /** Sanitized HTML generated by the editor. */
    private String bodyHtml;
    private String coverImageUrl;
    private Status status = Status.DRAFT;
    private boolean featured;
    private List<String> channels = new ArrayList<>();
    private List<String> tags = new ArrayList<>();
    private String legacySource;
    private Instant createdAt;
    private Instant updatedAt;
    private Instant publishedAt;
}
