### Lookup
POST http://localhost:8080/lookup
Accept: application/json
Content-Type: application/json

{
  "league_name": "DBBL  BB3"
}

### Create league collection
POST http://localhost:8080/leagueCollection/94dd6ae4-83fa-11ee-b910-02000090a64f
