### Authenticate
POST https://warp-scores.eu.auth0.com/oauth/token
Content-Type: application/json

{
  "client_id": "{{clientId}}",
  "client_secret": "{{clientSecret}}",
  "audience": "warp-scores-backend",
  "grant_type":"client_credentials"
}
> {%
    client.global.set("auth_token", response.body.access_token);
%}


### Status
GET {{backendBaseUrl}}/status
Accept: application/json

### Lookup
POST {{backendBaseUrl}}/lookup
Accept: application/json
Content-Type: application/json

{
  "league_name": "DBBL  BB3"
}

### Relaod matches
GET {{backendBaseUrl}}/matches/reload


### League
GET {{backendBaseUrl}}/leagues/94dd6ae4-83fa-11ee-b910-02000090a64f
Accept: application/json

### Image
GET {{backendBaseUrl}}/img/logo/Logo_Community_Supported_Competitions

Accept: application/json
Content-Type: application/json

{
  "league_name": "DBBL  BB3"
}

###
GET {{backendBaseUrl}}/contests/competition/6307c66a-a04e-11ee-a745-02000090a64f
Accept: application/json
Content-Type: application/json

### Create league collection
POST {{backendBaseUrl}}/leagueCollection/94dd6ae4-83fa-11ee-b910-02000090a64f
Authorization: Bearer {{auth_token}}

### Create league collection
GET {{backendBaseUrl}}/userPermissions
Authorization: Bearer {{auth_token}}


### check user permission
GET {{backendBaseUrl}}/userPermissions

### get arena races
GET {{backendBaseUrl}}/arena/fdcd5dde-e529-11ee-bbf2-0200000e1421/info

### get arena races
GET {{backendBaseUrl}}/arena/fdcd5dde-e529-11ee-bbf2-0200000e1421/info/goblin

### get arena contests for race and runtype
GET {{backendBaseUrl}}/arena/fdcd5dde-e529-11ee-bbf2-0200000e1421/race/goblin/completed/2/8



### get arena top coaches
GET {{backendBaseUrl}}/arena/fdcd5dde-e529-11ee-bbf2-0200000e1421/topCoaches

### get arena contests for coach
GET {{backendBaseUrl}}/arena/fdcd5dde-e529-11ee-bbf2-0200000e1421/coach/5522f49f-397f-11ee-af36-020000a4d571


### Create an admin contest
POST {{backendBaseUrl}}/contests/competition/72fbe403-a786-11ef-aaf1-bc24112ec32e
Authorization: Bearer {{auth_token}}
Content-Type: application/json

