import React,{useEffect,useState} from 'react';
import {Alert,AlertIcon,Badge,Box,Button,Checkbox,FormControl,FormLabel,Heading,HStack,Input,Modal,ModalBody,ModalCloseButton,ModalContent,ModalHeader,ModalOverlay,NumberInput,NumberInputField,Stack,Table,Tbody,Td,Text,Textarea,Th,Thead,Tr,VStack} from '@chakra-ui/react';
import WarpScoresApiService from '../../WarpScoresApiService';

const relativeAge=value=>{if(!value)return '—';const date=new Date(value),seconds=Math.max(0,Math.floor((Date.now()-date.getTime())/1000));if(Number.isNaN(seconds))return value;if(seconds<3600)return `${Math.max(1,Math.floor(seconds/60))} min ago`;if(seconds<86400)return `${Math.floor(seconds/3600)} h ago`;return `${Math.floor(seconds/86400)} days ago`;};

export default function ReplaySweeperAdmin({auth}){
  const[status,setStatus]=useState(null),[logs,setLogs]=useState([]),[replays,setReplays]=useState([]),[files,setFiles]=useState([]),[importResults,setImportResults]=useState([]),[inspect,setInspect]=useState(null),[password,setPassword]=useState(''),[challenge,setChallenge]=useState(null),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=()=>Promise.all([WarpScoresApiService.replaySweeperStatus(...auth),WarpScoresApiService.replaySweeperLogs(...auth),WarpScoresApiService.replaySweeperReplays(...auth)]).then(([s,l,r])=>{setStatus(s);setLogs(l);setReplays(r)}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const interval=setInterval(load,status?.running?2000:30000);return()=>clearInterval(interval)},[status?.running]); // eslint-disable-line react-hooks/exhaustive-deps
  const run=async action=>{setBusy(true);setError('');try{return await action()}catch(e){setError(e?.response?.data?.message||e.message)}finally{setPassword('');setBusy(false)}};
  const accept=result=>{if(result.status==='GUARD_REQUIRED')setChallenge(result);if(result.status==='AUTHENTICATED'){setChallenge(null);load()}};
  const openInspect=replay=>run(()=>WarpScoresApiService.inspectReplay(replay.matchId,...auth).then(data=>setInspect({replay,text:JSON.stringify(data,null,2)})));
  const downloadInspect=()=>{const url=URL.createObjectURL(new Blob([inspect.text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${inspect.replay.gameId||inspect.replay.matchId}.inspect.json`;link.click();URL.revokeObjectURL(url);};
  if(!status)return <Box borderWidth="1px" borderRadius="md" p={4}><Text>Loading replay service…</Text></Box>;
  const needsAuth=!status.credentialConfigured||!status.credentialValid;
  return <Box borderWidth="1px" borderRadius="md" p={4}><Heading size="md" mb={3}>BB3 replay sweeper</Heading>
    {needsAuth&&<Alert status="warning" mb={4}><AlertIcon/>{status.credentialConfigured?'The Steam ticket has expired and must be renewed.':'No replay service Steam account has been authenticated.'}</Alert>}
    {error&&<Alert status="error" mb={4}><AlertIcon/>{error}</Alert>}
    <Stack direction={{base:'column',lg:'row'}} align="end" spacing={3}>
      <Checkbox pb={2} isChecked={status.enabled} onChange={e=>setStatus({...status,enabled:e.target.checked})}>Enabled</Checkbox>
      <FormControl><FormLabel>Steam username</FormLabel><Input value={status.steamUsername||''} onChange={e=>setStatus({...status,steamUsername:e.target.value})}/></FormControl>
      <FormControl><FormLabel>Cron</FormLabel><Input value={status.cron} onChange={e=>setStatus({...status,cron:e.target.value})}/></FormControl>
      <FormControl><FormLabel>Time zone</FormLabel><Input value={status.zoneId} onChange={e=>setStatus({...status,zoneId:e.target.value})}/></FormControl>
      <FormControl maxW="8rem"><FormLabel>Batch size</FormLabel><NumberInput min={1} max={50} value={status.batchSize} onChange={(_,v)=>setStatus({...status,batchSize:v})}><NumberInputField/></NumberInput></FormControl>
      <Button onClick={()=>run(()=>WarpScoresApiService.updateReplaySweeper(status,...auth).then(setStatus))}>Save</Button>
      <Button isLoading={status.running} loadingText="Syncing replays" isDisabled={busy||needsAuth||status.running} onClick={()=>run(()=>WarpScoresApiService.runReplaySweeper(...auth).then(setStatus))}>Sync replays</Button>
    </Stack>
    <Text color="gray.500" fontSize="sm" mt={2}>Default: 05:00 Europe/Stockholm. Last run: {status.lastCompletedAt||'never'} · downloaded: {status.lastDownloaded||0}</Text>
    {challenge?<Stack mt={4} maxW="md"><Text>{challenge.method==='device_confirmation'?'Approve in the Steam app, then continue.':'Enter the Steam Guard code.'}</Text>{challenge.method!=='device_confirmation'&&<Input value={code} onChange={e=>setCode(e.target.value)}/>}<Button colorScheme="blue" isLoading={busy} onClick={()=>run(()=>challenge.method==='device_confirmation'?WarpScoresApiService.confirmReplaySweeperGuard(challenge.challengeId,...auth).then(accept):WarpScoresApiService.replaySweeperGuardCode(challenge.challengeId,code,...auth).then(accept))}>Continue</Button></Stack>:
      needsAuth&&<Stack mt={4} maxW="md"><FormControl><FormLabel>Steam password</FormLabel><Input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></FormControl><Button colorScheme="blue" isDisabled={!status.steamUsername||!password} isLoading={busy} onClick={()=>run(()=>WarpScoresApiService.authenticateReplaySweeper({username:status.steamUsername,password},...auth).then(accept))}>Authenticate replay account</Button></Stack>}
    <Heading size="sm" mt={5} mb={2}>Replay artifacts and analysis</Heading>
    <Stack direction={{base:'column',md:'row'}} align={{md:'end'}} mb={4}><FormControl><FormLabel>Import local .bbr files</FormLabel><Input type="file" accept=".bbr" multiple p={1} onChange={event=>setFiles([...event.target.files])}/></FormControl><Button colorScheme="blue" isDisabled={!files.length||busy} onClick={()=>run(()=>WarpScoresApiService.importReplays(files,...auth).then(result=>{setImportResults(result);setFiles([]);return load()}))}>Import {files.length||''}</Button></Stack>
    {importResults.length>0&&<VStack align="stretch" mb={4}>{importResults.map((result,index)=><HStack key={`${result.fileName}-${index}`}><Badge colorScheme={result.imported?'green':'red'}>{result.imported?'IMPORTED':'SKIPPED'}</Badge><Text fontSize="sm">{result.fileName}{result.matchId?` → ${result.matchId}`:''}{result.error?` · ${result.error}`:''}</Text></HStack>)}</VStack>}
    <Text fontSize="sm" color="gray.500" mb={2}>Only recent attempts inside the configured replay availability window are shown. Failed recent downloads are at risk of being lost when Steam removes them.</Text>
    <Box overflowX="auto"><Table size="sm"><Thead><Tr><Th>Match</Th><Th>Played</Th><Th>Replay</Th><Th>Analysis</Th><Th>Original / compact</Th><Th/></Tr></Thead><Tbody>{replays.map(replay=>{const downloaded=replay.status==='DOWNLOADED';return <Tr key={replay.matchId}><Td><Text fontWeight="semibold">{replay.teams?.join(' – ')||'Unknown match'}</Text>{replay.competitionName&&<Text fontSize="xs" color="gray.500">{replay.competitionName}</Text>}<Text fontSize="xs" color="gray.400">{replay.matchId}</Text></Td><Td whiteSpace="nowrap"><Text>{relativeAge(replay.playedAt)}</Text><Text fontSize="xs" color="gray.500">{replay.playedAt||'—'}</Text></Td><Td><Badge colorScheme={downloaded?'green':'red'}>{downloaded?'SAVED':'AT RISK'}</Badge>{replay.error&&<Text maxW="18rem" fontSize="xs" color="red.500">{replay.error}</Text>}</Td><Td><Badge colorScheme={!downloaded?'gray':replay.analysisStatus==='PROCESSED'?'green':replay.analysisStatus==='FAILED'?'red':'orange'}>{downloaded?(replay.analysisStatus||'PENDING'):'NOT AVAILABLE'}</Badge>{replay.analysisError&&<Text maxW="18rem" fontSize="xs" color="red.500">{replay.analysisError}</Text>}</Td><Td whiteSpace="nowrap">{replay.originalSize?`${Math.round(replay.originalSize/1024)} KiB`:'—'} / {replay.compactSize?`${Math.round(replay.compactSize/1024)} KiB`:'—'}</Td><Td><HStack><Button size="xs" isDisabled={busy||!downloaded} onClick={()=>openInspect(replay)}>Inspect</Button><Button size="xs" isDisabled={busy||!downloaded} onClick={()=>run(()=>WarpScoresApiService.analyzeReplay(replay.matchId,...auth).then(load))}>Analyze again</Button></HStack></Td></Tr>})}</Tbody></Table></Box>
    <Heading size="sm" mt={5} mb={2}>Administrator log</Heading><VStack align="stretch" maxH="16rem" overflowY="auto">{logs.map(entry=><HStack key={entry.id} borderBottomWidth="1px" py={1}><Badge colorScheme={entry.level==='ERROR'?'red':entry.level==='WARN'?'orange':'blue'}>{entry.level}</Badge><Text fontSize="sm" flex="1">{entry.message}</Text><Text color="gray.500" fontSize="xs">{entry.createdAt}</Text></HStack>)}{!logs.length&&<Text color="gray.500">No replay runs logged yet.</Text>}</VStack>
    <Modal size="6xl" isOpen={Boolean(inspect)} onClose={()=>setInspect(null)}><ModalOverlay/><ModalContent><ModalHeader>Parsed replay · {inspect?.replay?.teams?.join(' – ')||inspect?.replay?.matchId}</ModalHeader><ModalCloseButton/><ModalBody pb={6}><Alert status="warning" mb={3}><AlertIcon/>Parser v1 is structurally lossless but its statistical interpretation is experimental. Unknown enums are shown raw.</Alert><HStack mb={3}><Button onClick={()=>navigator.clipboard.writeText(inspect.text)}>Copy full JSON</Button><Button onClick={downloadInspect}>Download inspect JSON</Button></HStack><Textarea value={inspect?.text?.slice(0,100000)||''} readOnly fontFamily="mono" minH="30rem"/><Text fontSize="xs" color="gray.500">Preview is limited to 100,000 characters; Copy and Download contain the complete parsed replay.</Text></ModalBody></Modal>
  </Box>;
}
