import React,{useEffect,useState} from 'react';
import { Button,Checkbox,Heading,HStack,Select,Spinner,Stack,Tab,TabList,TabPanel,TabPanels,Tabs,Text } from '@chakra-ui/react';
import Navigation from '../components/misc/Navigation';
import WarpScoresApiService from '../WarpScoresApiService';
import useAuth0WithUserPermissions from '../hooks/useAuth0WithUserPermissions';
import {CategoryTabs,TeamTable,VersusTable} from '../components/statistics/StatisticsTables';
export default function StatisticsPage(){const auth=useAuth0WithUserPermissions(),[systems,setSystems]=useState([]),[systemId,setSystemId]=useState(''),[overview,setOverview]=useState(null),[seasonId,setSeasonId]=useState(''),[season,setSeason]=useState(null),[marathon,setMarathon]=useState(null),[edition,setEdition]=useState('ALL'),[merge,setMerge]=useState(false),[page,setPage]=useState(0),[myTeamsOnly,setMyTeamsOnly]=useState(false),[myPlayersOnly,setMyPlayersOnly]=useState(false),[personal,setPersonal]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
useEffect(()=>{WarpScoresApiService.publicLeagueSystems().then(s=>{setSystems(s);setSystemId((s.find(x=>x.primary)||s[0])?.id||'')}).catch(e=>setError(e.message))},[]);
useEffect(()=>{if(!systemId)return;setLoading(true);Promise.all([WarpScoresApiService.leagueSystemOverview(systemId),WarpScoresApiService.marathonStatistics(systemId,{edition,mergeTeamsByName:merge,page})]).then(([o,m])=>{setOverview(o);setSeasonId(v=>v||[...(o.seasons||[])].sort((a,b)=>(b.sequence??0)-(a.sequence??0))[0]?.id||'');setMarathon(m)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[systemId,edition,merge,page]);
useEffect(()=>{if(systemId&&seasonId)WarpScoresApiService.seasonStatistics(systemId,seasonId).then(setSeason).catch(e=>setError(e.message))},[systemId,seasonId]);
useEffect(()=>{if(!systemId||!auth.authenticationReady||!auth.isAuthenticated){setPersonal(null);return;}WarpScoresApiService.personalStatistics(systemId,auth.getAccessTokenSilently,auth.getAccessTokenWithPopup).then(setPersonal).catch(()=>setPersonal(null))},[systemId,auth.authenticationReady,auth.isAuthenticated,auth.getAccessTokenSilently,auth.getAccessTokenWithPopup]);
const mineToggle=(type)=><Checkbox mb={3} isChecked={type==='team'?myTeamsOnly:myPlayersOnly} onChange={e=>type==='team'?setMyTeamsOnly(e.target.checked):setMyPlayersOnly(e.target.checked)}>{type==='team'?'My teams only':'My players only'}</Checkbox>;
return <Stack><Navigation currentPage="statistics"/><Heading>Statistics</Heading><HStack wrap="wrap"><Select maxW="20rem" value={systemId} onChange={e=>{setSystemId(e.target.value);setSeasonId('');setPage(0)}}>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>{loading&&<Spinner size="sm"/>}</HStack>{error&&<Text color="red.500">{error}</Text>}<Tabs variant="soft-rounded" isLazy><TabList><Tab>Season</Tab><Tab>Marathon</Tab>{auth.authenticationReady&&auth.isAuthenticated&&<Tab>Coach versus</Tab>}</TabList><TabPanels><TabPanel px={0}><Select mb={4} maxW="20rem" value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{overview?.seasons?.map(s=><option key={s.id} value={s.id}>{s.name||`Season ${s.number}`}</option>)}</Select><Tabs isFitted variant="enclosed"><TabList><Tab>Players</Tab><Tab>Teams</Tab></TabList><TabPanels><TabPanel px={0}>{mineToggle('player')}<CategoryTabs type="player" categories={season?.players} mineOnly={myPlayersOnly}/></TabPanel><TabPanel px={0}>{mineToggle('team')}<CategoryTabs type="team" categories={season?.teams} mineOnly={myTeamsOnly}/></TabPanel></TabPanels></Tabs></TabPanel><TabPanel px={0}><Stack direction={{base:'column',md:'row'}} mb={4}><Select maxW="14rem" value={edition} onChange={e=>{setEdition(e.target.value);setPage(0)}}><option value="ALL">All editions</option>{marathon?.availableEditions?.map(e=><option key={e}>{e}</option>)}</Select><Checkbox isChecked={merge} onChange={e=>{setMerge(e.target.checked);setPage(0)}}>Merge teams with the same name</Checkbox></Stack>{edition==='ALL'&&<Text fontSize="sm" color="gray.500" mb={3}>Only player statistics comparable across rulesets are shown.</Text>}<Tabs isFitted variant="enclosed"><TabList><Tab>Teams</Tab><Tab>Players</Tab></TabList><TabPanels><TabPanel px={0}>{mineToggle('team')}<TeamTable entries={marathon?.teams?.content||[]} mineOnly={myTeamsOnly}/><HStack justify="space-between" mt={3}><Button isDisabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</Button><Text>Page {page+1} of {marathon?.teams?.totalPages||1}</Text><Button isDisabled={page+1>=(marathon?.teams?.totalPages||1)} onClick={()=>setPage(p=>p+1)}>Next</Button></HStack></TabPanel><TabPanel px={0}>{mineToggle('player')}<CategoryTabs type="player" categories={marathon?.players} mineOnly={myPlayersOnly}/></TabPanel></TabPanels></Tabs></TabPanel>{auth.authenticationReady&&auth.isAuthenticated&&<TabPanel px={0}>{!personal?.coaches?.length?<Text>No coaches claimed yet. Claim your BB1/BB2/BB3 coach names under Account.</Text>:<VersusTable rows={personal?.versus}/>}</TabPanel>}</TabPanels></Tabs></Stack>}
