server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native

spring:
  web:
    resources:
      static-locations: classpath=/public
    cors:
      allowed-origins: "${FRONTEND_URI:http://localhost:8022}"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  cache:
    cache-names: "NafCoach"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URI:http://localhost:8022}
          jwk-set-uri: ${AUTH_URI:http://localhost:8022}/.well-known/jwks.json
          jws-algorithms: RS256

okta:
  oauth2:
    issuer: ${AUTH_URI:http://localhost:8022}
    audience: ${OKTA_AUDIENCE:api://default}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always