server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native

spring:
  config:
    import: optional:file:../.env[.properties]
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb+srv://${MONGO_USER:USER}:${MONGO_PASS:PASS}@nst-cluster.9a9lw.mongodb.net/cyanidebowl?retryWrites=true&w=majority&authSource=admin}
  web:
    resources:
      static-locations: classpath=/public
    cors:
      allowed-origins: "${FRONTEND_URI:http://localhost:8022}"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  cache:
    cache-names: "NafCoach"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
          jws-algorithms: RS256
