ARENA_SEASON_07_NAME=Norsca Arena
OPEN\ LADDER=Open Ladder
official_ladder_season_01=Official Ladder Season 01
official_ladder_season_02=Official Ladder Season 02
official_ladder_season_03=Official Ladder Season 03
official_ladder_season_04=Official Ladder Season 04
official_ladder_season_05=Official Ladder Season 05
official_ladder_season_06=Official Ladder Season 06
official_ladder_season_07=Official Ladder Season 07
official_halfling_vs_goblin_competition=Official Halfling vs Goblin Competition
