ARENA_SEASON_07_NAME=Norsca Arena
ARENA_SEASON_07_LOGO=Norse_12
ARENA_SEASON_08_NAME=Lustria Arena
ARENA_SEASON_08_LOGO=Amazon_12
official_halfling_vs_goblin_competition_LOGO=Logo_Season_06_06
community_event_02=Amazon Clash
OPEN\ LADDER=Open Ladder
official_ladder_season_01=Official Ladder Season 01
official_ladder_season_02=Official Ladder Season 02
official_ladder_season_03=Official Ladder Season 03
official_ladder_season_04=Official Ladder Season 04
official_ladder_season_05=Official Ladder Season 05
official_ladder_season_06=Official Ladder Season 06
official_ladder_season_07=Official Ladder Season 07
official_ladder_season_08=Official Ladder Season 08
official_ladder_season_09=Official Ladder Season 09
official_ladder_season_10=Official Ladder Season 10
official_ladder_season_07_LOGO=Logo_Season_07_06
official_ladder_season_08_LOGO=Logo_Season_08_06
official_halfling_vs_goblin_competition=Official Halfling vs Goblin Competition
