# ##############################################################################
# Misc #########################################################################

### Get info about api
GET https://web.cyanide-studio.com/ws/?bb=3&key={{apiKey}}

### Get status
GET https://web.cyanide-studio.com/ws/cya/status/?key={{apiKey}}

# ##############################################################################
# Lookup #######################################################################

### Lookup league
GET https://web.cyanide-studio.com/ws/bb3/lookup/?league=NAF BB3 Kickoff&platform=pc&key={{apiKey}}

### Lookup coach
GET https://web.cyanide-studio.com/ws/bb3/lookup/?coach=naytsyrhc&platform=pc&key={{apiKey}}

# ##############################################################################
# League #######################################################################

### Get leagues
GET https://web.cyanide-studio.com/ws/bb3/leagues/?league=DBBL  BB3&limit=100&platform=pc&key={{apiKey}}

### Get league
GET https://web.cyanide-studio.com/ws/bb3/league/?id=94dd6ae4-83fa-11ee-b910-02000090a64f&key={{apiKey}}

### Get competitions
GET https://web.cyanide-studio.com/ws/bb3/competitions/?league_id=c9c30e36-5ca5-11ee-af36-020000a4d571&key={{apiKey}}

# ##############################################################################
# Competition ##################################################################

### Get coaches
GET https://web.cyanide-studio.com/ws/bb3/coaches/?competition=DBBL S1 Division 1&limit=10&platform=pc&key={{apiKey}}

### Get teams
GET https://web.cyanide-studio.com/ws/bb3/teams/?league_id=94dd6ae4-83fa-11ee-b910-02000090a64f&competition_id=e8848221-a04e-11ee-a745-02000090a64f&platform=pc&key={{apiKey}}&order=finished

### Get contests * by league_id for status Played
GET https://web.cyanide-studio.com/ws/bb3/contests/?status=Played&league_id=94dd6ae4-83fa-11ee-b910-02000090a64f&key={{apiKey}}

### Get contests * by league_id for status Validated
GET https://web.cyanide-studio.com/ws/bb3/contests/?status=Validated&order=finished&limit=5&league_id=94dd6ae4-83fa-11ee-b910-02000090a64f&key={{apiKey}}

### Get contests * by competition_id
GET https://web.cyanide-studio.com/ws/bb3/contests/?status=*&competition_id=558803fb-1878-11ef-895c-bc24112ec32e&platform=pc&key={{apiKey}}

### Get matches
GET https://web.cyanide-studio.com/ws/bb3/matches/?league_id=94dd6ae4-83fa-11ee-b910-02000090a64f&start=2024-07-04T13:04:46&platform=pc&key={{apiKey}}

, competition_name=null, competition_id=null, start=Sat Jul 06 13:04:56 CEST 2024,

### Get matches (ordered)
GET https://web.cyanide-studio.com/ws/bb3/matches/?league_id=94dd6ae4-83fa-11ee-b910-02000090a64f&startDate=2023-12-01&platform=pc&key={{apiKey}}&order=finished

### Get match by id
GET https://web.cyanide-studio.com/ws/bb3/match/?match_id=bcc5e39e-1de0-11ef-895c-bc24112ec32e&platform=pc&key={{apiKey}}

# ##############################################################################
# Team #########################################################################

### Get team
GET https://web.cyanide-studio.com/ws/bb3/team/?id=1749c704-e328-11ee-a745-02000090a64f&platform=pc&key={{apiKey}}

### Get team matches
GET https://web.cyanide-studio.com/ws/bb3/teammatches/?team_id=7e69a4ba-87f1-11ee-b910-02000090a64f&platform=pc&key={{apiKey}}

# ##############################################################################
# Others #######################################################################

### Get halloffame (NOT YET IMPLEMENTED)
GET https://web.cyanide-studio.com/ws/bb3/halloffame/?league=NAF BB3 Kickoff&limit=10&platform=pc&key={{apiKey}}

### Get ladder
GET https://web.cyanide-studio.com/ws/bb3/ladder/?league=NAF BB3 Kickoff&limit=100&platform=pc&key={{apiKey}}
